drivers:power:nopmi_chg_common: Disable unused variable 'nopmi_charger_ic'
error: unused variable 'nopmi_charger_ic' [-Werror,-Wunused-variable]
static NOPMI_CHARGER_IC_TYPE nopmi_charger_ic = NOPMI_CHARGER_IC_NONE;

* because longcheer did via battery_class attribute .

Signed-off-by: muralivijay <muralidharan9845@gmail.com>