max77729: Define missing module licence.
ERROR: modpost: missing MODULE_LICENSE() in drivers/mfd/maxim/max77729-irq.lto.o
ERROR: modpost: missing MODULE_LICENSE() in drivers/usb/typec/maxim/max77729_cc.lto.o
ERROR: modpost: missing MODULE_LICENSE() in drivers/usb/typec/maxim/max77729_pd.lto.o
ERROR: modpost: missing MODULE_LICENSE() in drivers/usb/typec/maxim/max77729_alternate.lto.o
ERROR: modpost: missing MODULE_LICENSE() in drivers/usb/typec/maxim/max77729-muic.lto.o

Signed-off-by: muralivijay <muralidharan9845@gmail.com>